{
 "title": "Cosmos Validator",
 "description": "Stats of a Cosmos validator",
 "tags": [
  "cosmos",
  "blockchain",
  "validator"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "chain_id",
    "query": {
     "query": "label_values(cosmos_validators_status, chain_id)"
    }
   },
   {
    "name": "moniker",
    "label": "moniker",
    "query": {
     "query": "label_values(cosmos_validator_active, moniker)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_memory_MemTotal_bytes, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Validator health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "\r\n<table style=\"width:100%; height:100%;border:0px solid black;\">\r\n     <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \"><center><img width=\"300px\" src=\"https://i.hizliresim.com/aozz4we.png\" /></td>\r\n</table>"
   }
  },
  {
   "title": "Active",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_active{chain_id=\"$chain_id\", moniker=\"$moniker\"}"
    }
   ]
  },
  {
   "title": "Connected peers",
   "type": "stat",
   "description": "Number of peers node's connected to\n\n(Need to change Threshold)",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Missed blocks",
   "type": "stat",
   "description": "Number of missed blocks",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cosmos_validator_missed_blocks{chain_id=\"$chain_id\", moniker=\"$moniker\"}"
    }
   ]
  },
  {
   "title": "Missed blocks",
   "type": "timeseries",
   "description": "Validator missed blocks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cosmos_validators_missed_blocks{chain_id=\"$chain_id\", moniker=\"$moniker\"}"
    }
   ]
  },
  {
   "title": "Syncing",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_state_syncing{chain_id=\"$chain_id\"}"
    }
   ]
  },
  { "title": "Chain health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Block height",
   "type": "stat",
   "description": "Height of the chain",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_height{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Online validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators-tendermint_consensus_missing_validators{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Offline validators",
   "type": "stat",
   "description": "Number of validators who did not sign",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Confirmed Tx",
   "type": "stat",
   "description": "Total number of transactions committed",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_total_txs{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Validators missing blocks",
   "type": "stat",
   "description": "Number of validators missing blocks",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validators_missed_blocks{chain_id=\"$chain_id\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Top validators missing blocks",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 10 },
   "targets": [
    {
     "expr": "sort_desc(topk(10, cosmos_validators_missed_blocks{chain_id=\"$chain_id\"} > 0))"
    }
   ]
  },
  {
   "title": "Total bonded tokens",
   "type": "stat",
   "description": "The total number of bonded tokens in the network",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Offline: bonded tokens",
   "type": "stat",
   "description": "Total voting power of the missing validators",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators_power{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Offline: voting power %",
   "type": "stat",
   "description": "Total voting power of the missing validators",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(tendermint_consensus_missing_validators_power{chain_id=\"$chain_id\"} / tendermint_consensus_validators_power{chain_id=\"$chain_id\"})"
    }
   ]
  },
  {
   "title": "Unconfirmed Tx",
   "type": "stat",
   "description": "Number of uncommitted transactions",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_size{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Top missed blocks",
   "type": "stat",
   "description": "Number of highest missed blocks for validators on chain",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(cosmos_validators_missed_blocks{chain_id=\"$chain_id\"})"
    }
   ]
  },
  {
   "title": "Blocks per minute",
   "type": "stat",
   "description": "Number of blocks produced last minute",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(increase(tendermint_consensus_height{chain_id=\"$chain_id\"}[1m]))"
    }
   ]
  },
  {
   "title": "Blocks per minute",
   "type": "timeseries",
   "description": "Number of block produced last minute",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(tendermint_consensus_height{chain_id=\"$chain_id\"}[1m])"
    }
   ]
  },
  {
   "title": "Block Size (bytes)",
   "type": "timeseries",
   "description": "Block size in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes{chain_id=\"$chain_id\"}"
    }
   ]
  },
  { "title": "Validator stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Jailed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validator_jailed{chain_id=\"$chain_id\", moniker=\"$moniker\"}"
    }
   ]
  },
  {
   "title": "Rank",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(cosmos_validator_rank{chain_id=\"$chain_id\", moniker=\"$moniker\"})",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "Total delegations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cosmos_validator_delegations{chain_id=\"$chain_id\", moniker=\"$moniker\"}) by (denom)",
     "legendFormat": "{{ denom }}"
    }
   ]
  },
  {
   "title": "Commission rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validator_commission_rate{chain_id=\"$chain_id\", moniker=\"$moniker\"}"
    }
   ]
  },
  {
   "title": "Delegations count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validator_delegations{chain_id=\"$chain_id\", moniker=\"$moniker\"})",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "Redelegations count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validator_redelegations{chain_id=\"$chain_id\", moniker=\"$moniker\"}) OR on() vector(0)",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "Unbondings count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validator_unbondings{chain_id=\"$chain_id\", moniker=\"$moniker\"}) OR on() vector(0)",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "Delegations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(cosmos_validator_delegations{chain_id=\"$chain_id\", moniker=\"$moniker\"}) by (moniker, denom)",
     "legendFormat": "{{ moniker }}, {{ denom }}"
    }
   ]
  },
  {
   "title": "Delegations",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cosmos_validator_delegations{chain_id=\"$chain_id\", moniker=\"$moniker\"}"
    }
   ]
  },
  {
   "title": "Redelegations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cosmos_validator_redelegations{chain_id=\"$chain_id\", moniker=\"$moniker\"}) by (moniker, denom)",
     "legendFormat": "{{ moniker }}, {{ denom }}"
    }
   ]
  },
  {
   "title": "Redelegations",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "cosmos_validator_redelegations{chain_id=\"$chain_id\", moniker=\"$moniker\"} "
    }
   ]
  },
  {
   "title": "Unbondings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cosmos_validator_unbondings{chain_id=\"$chain_id\", moniker=\"$moniker\"}) by (moniker, denom)",
     "legendFormat": "{{ moniker }}, {{ denom }}"
    }
   ]
  },
  {
   "title": "Unbondings",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 45 },
   "targets": [
    {
     "expr": "cosmos_validator_unbondings{chain_id=\"$chain_id\", moniker=\"$moniker\"} "
    }
   ]
  },
  {
   "title": "Rewards",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cosmos_validator_rewards{chain_id=\"$chain_id\", moniker=\"$moniker\"}",
     "legendFormat": "{{ moniker }}, {{ denom }}"
    }
   ]
  },
  {
   "title": "Commission",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "cosmos_validator_commission{chain_id=\"$chain_id\", moniker=\"$moniker\"}",
     "legendFormat": "{{ moniker }}, {{ denom }}"
    }
   ]
  },
  { "title": "Hardware health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Uptime CT",
   "type": "stat",
   "description": "Core node uptime",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{instance=\"$instance\"})",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$instance\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "System Health",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 4, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{instance=~\"$instance\", mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$instance\"} / (node_memory_MemTotal_bytes{instance=~\"$instance\"})))* 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{instance=~\"$instance\"} / node_memory_SwapTotal_bytes{instance=~\"$instance\"})) * 100",
     "legendFormat": "SWAP"
    },
    {
     "expr": "100 - (node_filesystem_free_bytes{instance=~\"$instance\", device=\"/dev/sda2\"} *100 / node_filesystem_size_bytes{instance=~\"$instance\", device=\"/dev/sda2\"})",
     "legendFormat": "Disk"
    },
    {
     "expr": "100 - (node_filesystem_free_bytes{instance=~\"$instance\", device=\"/dev/sda1\"} *100 / node_filesystem_size_bytes{instance=~\"$instance\", device=\"/dev/sda1\"})",
     "legendFormat": "Boot"
    }
   ]
  },
  {
   "title": "Currently open file descriptor",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Free space for each partition",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 60 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$instance',fstype=~\"ext4|xfs\"}"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$instance',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$instance',fstype=~\"ext4|xfs\"})"
    },
    {}
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg. System Load",
   "type": "graph",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\"}*100",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=~\"$instance\"}*100",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=~\"$instance\"}*100",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "CPU usage, disk I/O operations per second take time（%）",
   "type": "graph",
   "description": "node_disk_io_time_seconds_total：\nThe number of milliseconds the disk spends on input/output operations. This value is the accumulated value.（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\nCalculate the rate per second: (last value - last previous value) / timestamp difference, that is, the percentage of time that the disk spends on I/O operations in 1 second.",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 65 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"system\"}[1m]))",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"user\"}[1m]))",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"iowait\"}[1m]))",
     "legendFormat": "Iowait"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{device}}_% of I/O operations per second"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"system\"}[1m]))",
     "legendFormat": "test"
    }
   ]
  },
  {
   "title": "Disk read and write rate（IOPS）",
   "type": "graph",
   "description": "Reads completed: Reads per second per disk partition\n\nWrites completed: Number of writes per second per disk partition\n\nIO now Number of input/output requests being processed per disk partition per second",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "iops", "label": "Read (-) / write（+）I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk read and write capacity",
   "type": "graph",
   "description": "Read bytes The number of bits read per second per disk partition\nWritten bytes The number of bits written per second per disk partition",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
   "yaxes": [
    { "format": "Bps", "label": "Read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk IO read and write time",
   "type": "graph",
   "description": "Read time ms Number of seconds per disk partition read operation\n\nWrite time ms Number of seconds spent per disk partition write operation\n\nIO time ms Number of seconds spent per disk partition input/output operation\n\n IO time weighted Weighted seconds spent per disk partition input/output operation",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 76 },
   "yaxes": [
    { "format": "s", "label": "Read (-) / write (+) " }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "bps", "label": "Upload (-) / Download（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$instance',device!~'tap.*'}[5m])*8",
     "legendFormat": "{{device}}_in download"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$instance',device!~'tap.*'}[5m])*8",
     "legendFormat": "{{device}}_out upload"
    }
   ]
  },
  {
   "title": "TCP Connection situation",
   "type": "graph",
   "description": "CurrEstab - TCP connections with current state ESTABLISHED or CLOSE-WAIT\n\nActiveOpens - TCP average connections that have been converted from CLOSED state to SYN-SENT state (within 1 minute)\n\nPassiveOpens - Directly from LISTEN state The average number of TCP connections to SYN-RCVD state (within 1 minute)\n\nTCP_all oc - the number of TCP sockets allocated (established, applied to sk_buff)\n\nTCP_inuse - in use (listening The number of TCP sockets \n\nTCP_tw - the number of TCP connections waiting to be closed",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$instance'}",
     "legendFormat": "ESTABLISHED"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$instance'}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~'$instance'}[1m])",
     "legendFormat": "ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~'$instance'}[1m])",
     "legendFormat": "PassiveOpens"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$instance'}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~'$instance'}",
     "legendFormat": "TCP_inuse"
    }
   ]
  }
 ]
}